# Site settings
title: Fonts and Layout for Global Scripts
email: simon@simon-cozens.org
baseurl: "/fonts-and-layout/" # the subpath of your site, e.g. /blog/
url: "http://simoncozens.github.io/" # the base hostname & protocol for your site
twitter_username: simoncozens
github_username:  simoncozens

# Build settings
markdown: kramdown
